## -*- Mode: makefile -*-
LIBXUL_SDK := $(shell pkg-config --variable=sdkdir libxul)

NSPR_INCLUDES = -I/usr/include/nspr4
NSPR_LIBS = -lplds4 -lplc4 -lnspr4 -lpthread -ldl

CHMLIB_INCLUDES = -I/usr/include
CHMLIB_LIBS = -lchm

include ./common.mk
