LIBXUL_SDK = $(shell pkg-config --variable=sdkdir libxul)

NSPR_INCLUDES = -I/usr/include/nspr
NSPR_LIBS = -lplds4 -lplc4 -lnspr4 -lpthread -ldl

CHMLIB_INCLUDES = -I/usr/include
CHMLIB_LIBS = -lchm

PYTHON2 = /usr/bin/python2
XPCOMCHM = libxpcomchm.so

include ./common.mk
